apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multitenant-ingress
  namespace: multitenant-frontend
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 31080
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            namespace: multitenant-auth
            port:
              number: 8001
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: users-service
            namespace: multitenant-users
            port:
              number: 8002
